config/routes.rb
Rails.application.routes.draw do
   devise_for :users,
   controllers: { registrations: 'registrations' }
   
   root 'posts#index'
   
   resources :users do
    member do
      get :following, :followers
    end
   end
   
   #get '/users/:id', to: 'users#show', as: 'user'

   resources :posts, only: %i(new create index show destroy) do
    resources :photos, only: %i(create)
   end
   resources :relationships,       only: [:create, :destroy]
   
end

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Copyright © Techpit
      </p>
    </div>
  </div>
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto align-items-center">
        <li>
          <%= link_to "Users", users_path %>
        </li>

        <li>
          <%= link_to "投稿", new_post_path, class: "btn btn-primary" %>
        </li>
        <li>
          <%= link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon" %>
        </li>
      </ul>
    </div>
  </div>
</nav>