config/routes.rb
Rails.application.routes.draw do
   devise_for :users,
   controllers: { registrations: 'registrations' }
   
   root 'posts#index'
   
   resources :users do
    member do
      get :following, :followers
    end
   end
   
   #get '/users/:id', to: 'users#show', as: 'user'

   resources :posts, only: %i(new create index show destroy) do
    resources :photos, only: %i(create)
   end
   resources :relationships,       only: [:create, :destroy]
   
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  
  accepts_nested_attributes_for :photos
   
  validates :user_id, presence: true
  validates :caption, presence: true, length: { maximum: 140 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post,  only: %i(show destroy)
  
  
  def index
    @posts = Post.limit(10).includes(:photos, :user).order('created_at DESC')
  end
  
  def show
    
  end
  

  def new
    @post = Post.new
    @post.photos.build
  end
  
  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  

  private
    def post_params
      params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
    end
    
    def set_post
      @post = Post.find_by(id: params[:id])
    end

  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>

        </div>
        
        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <% end %>

        <div class="card-body">
          <div class="row parts">
            <%= link_to "", "#", class: "love" %>
            <%= link_to "", "#", class: "comment" %>
          </div>
          <div><strong>「いいね！」10件</strong></div>
          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
            
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
            <hr>
            <div class="row parts">
              <form action="#" class="w-100">
                <div>
                  <textarea class="form-control comment-input border-0" placeholder="コメント..." rows="1"></textarea>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-profile-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く" %>
            </div>
          </div>
          <div class="mb-3">

            <%= f.fields_for :photos do |i| %>
              <%= i.file_field :image %>
            <% end %>

          </div>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@post.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>
            
            
            <%# ==========ここから追加する========== %>
            <% if @post.user_id == current_user.id %>
              <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
            <% end %>
            <%# ==========ここまで追加する========== %>
          </div>
          <div class="m-2">
            <strong>
              <%= @post.caption %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
            </div>
          </div>
        </div>
        <div class="row parts">
        </div>
        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
      </div>
    </div>
  </div>
</div>